[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""
idle_fg = "#928374"
info_bg = "#282828"
info_fg = "#98971a"
warning_fg = "#282828"

[[block]]
block = "focused_window"
format = " < $title.str > |"
[[block.click]]
button = "up"
cmd = "swaymsg workspace prev_on_output"
[[block.click]]
button = "down"
cmd = "swaymsg workspace next_on_output"

[[block]]
block = "privacy"
[[block.driver]]
name = "pipewire"

[[block]]
block = "music"
seek_step_secs = 3
format = " $combo.str(max_w:36) [$play] |"
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "sound"
max_vol = 100
show_volume_when_muted = true
headphones_indicator = true
step_width = 1
format = " $output_description.str(max_w:36){[$volume]|} "

[[block]]
block = "load"
format = " [$1m.eng(w:4), $5m.eng(w:4), $15m.eng(w:4)] "
interval = 60

[[block]]
block = "memory"
format = " [$mem_used.eng(w:4,prefix:Mi) / $mem_total.eng(prefix:Mi)] "
format_alt = " [$swap_used.eng(prefix:Mi) / $swap_total.eng(prefix:Mi)] "
interval = 30

[[block]]
block = "net"
format = " $ssid[$signal_strength] | Wired[$device] "
interval = 30

[[block]]
block = "battery"
full_format = " full[$percentage] "
charging_format = " $time_remaining til charged[$percentage] "
empty_format = " !!![$percentage] "
not_charging_format = " plugged[$percentage] "
missing_format = ""
format = " $time_remaining left[$percentage] "
interval = 30
good = 90

[[block]]
block = "time"
format = " $timestamp.datetime() "
[block.theme_overrides]
idle_fg = "#ebdbb2"
